### ISSUE TITLE
Stage 0'dan Stage 1'e geçiş hatası

### ISSUE THREAD

**Issue by LupusCaelum** [ybaspinar/Faruk-V#1]
Son promote işaretine tıkladığımda Java binary çöküyor ve tüm sistem kapanmakta. 10gb ram verdiğim halde bu durum oluyor java yanıt vermeyi kesiyor beklerken
Java son sürüm
Windows 10
Temiz kurulum ile denendi tekrar aynı hatayı verdi.

**Comment by ybaspinar** [comment]
Paket çöktüğü zaman oluşan crash dosyasını pastebin veya benzeri bir siteye yükleyip atabilirmisin

**Comment by LupusCaelum** [comment]
![Faruk V](https://user-images.githubusercontent.com/97120705/155308460-558e4745-e8d3-4360-b7e2-0ce60930b55d.png)
En baştan lahuncer dahil temiz bir kurulum daha yaptım uzun süre bekledikten sonra ekranda bu şekilde bir kasma oldu lakin 2 dakika gibi bir sürenin ardından bu sefer çökme olmadı ve bir sonraki bölüme geçişi tamamladı crash dosyası alamadım. Temizlerken crash dosyasını yedeklememiştim şimdilik sorun çözüldü.
Verdiğim rahatsızlıktan dolayı kusura bakmayın.
