### ISSUE TITLE
[Suggestion] Little Logistics Mod

### ISSUE THREAD

**Issue by DizzyDJW** [ybaspinar/Faruk-V#3]
**Mod Name**
Little Logistics

**Mod Description**
This mod adds little tug boats that can be used for various things, most importantly, fishing.

**Reason To Add Mod**
Sushi Go Crafting is in Faruk V but with such a LARGE world using Terraforged Terrain Generation, the ocean is thousands of block away, making Salmon a nightmare to come by. This would alleviate fishing in the early game, and as a bonus the little tug boats could conceivably be told to take rivers from the ocean to your base to drop off the fresh fish. Their recipes should be tweaked to require Create components, but should definitely be as early-game as Create, since they have a very vanilla-feel to them. and aren't very overpowered.

**Note**
A simpler, but less interesting mod to add, to alleviate salmon issues, could be Aquaculture 2. Their fishing rods could be used to more easily catch salmon.

**Comment by ybaspinar** [comment]
Usually azelza made decision about mods and configs so  im gone send this to him.
